### ISSUE TITLE
missing dependencies error

### ISSUE THREAD

**Issue by adamwatters** [Nodragem/twin-stick-shooter-starter-kit#2]
looks awesome! i'm hitting some dependency when i try to run

![Screenshot 2024-05-17 at 12 27 59 PM](https://github.com/Nodragem/twin-stick-shooter-starter-kit/assets/7673611/d472a82a-8ce2-437b-a51b-80fc881790b2)

**Comment by adamwatters** [comment]
![Screenshot 2024-05-17 at 12 31 03 PM](https://github.com/Nodragem/twin-stick-shooter-starter-kit/assets/7673611/fb4bbd7e-f26e-4fc0-9bcd-7a6d96ed6f8a)

If i run the main scene with `CMD + B`. Here's what I see.

**Comment by adamwatters** [comment]
sorry for breaking this into a couple comments 😅 

i get the error alert below if i try to open `main.tscn`, `level1.tscn`, and `level2.tscn`

![Screenshot 2024-05-17 at 12 38 19 PM](https://github.com/Nodragem/twin-stick-shooter-starter-kit/assets/7673611/27a00988-3560-4313-89ba-83d151e4b8da)

When I run the main scene (screenshot on previous comment), I see these errors in the Debugger console.
```
E 0:00:00:0847   open: res://kits/mesh_lib3.tres:1 - Parse Error: Saved with newer format version
  <C++ Source>   scene/resources/resource_format_text.cpp:1055 @ open()

E 0:00:00:0847   _load: Failed loading resource: res://kits/mesh_lib3.tres. Make sure resources have been imported by opening the project in the editor at least once.
  <C++ Error>    Condition "found" is true. Returning: Ref<Resource>()
  <C++ Source>   core/io/resource_loader.cpp:275 @ _load()

E 0:00:00:0866   _parse_ext_resource: res://scenes/level2/level2.tscn:42 - Parse Error: [ext_resource] referenced non-existent resource at: res://kits/mesh_lib3.tres
  <C++ Source>   scene/resources/resource_format_text.cpp:163 @ _parse_ext_resource()
```

i'm on Godot 4.2.2

**Comment by AnecAllods** [comment]
+1 on this issue
![image](https://github.com/Nodragem/twin-stick-shooter-starter-kit/assets/43345411/8c8a78b7-3e87-456f-a05c-f7a18be67215)
`--- GDScript language server started on port 6005 ---
  scene/resources/resource_format_text.cpp:448 - res://characters/PlayerEntity.tscn:5 - ext_resource, invalid UID: uid://cnt1c1t4mbygw - using text path instead: res://ui/game_data_store.tres
  scene/resources/resource_format_text.cpp:1055 - res://kits/mesh_lib3.tres:1 - Parse Error: Saved with newer format version
  Failed loading resource: res://kits/mesh_lib3.tres. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:284 - res://scenes/level2/level2.tscn:42 - Parse Error: 
  Failed loading resource: res://scenes/level2/level2.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:448 - res://ui/ControllerMenu.tscn:3 - ext_resource, invalid UID: uid://b5kvl5o6ywpt1 - using text path instead: res://ui/game_data_store.tres
  scene/resources/resource_format_text.cpp:284 - res://scenes/main.tscn:18 - Parse Error: 
  Failed loading resource: res://scenes/main.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  editor/editor_data.cpp:626 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
  scene/resources/resource_format_text.cpp:1584 - res://kits/meshlib_space_ground.tres:1 - Parse Error: Saved with newer format version
  scene/resources/resource_format_text.cpp:1584 - res://kits/mesh_lib3.tres:1 - Parse Error: Saved with newer format version`

**Comment by Nodragem** [comment]
the relevant line seems to be this one:
```
res://kits/mesh_lib3.tres:1 - Parse Error: Saved with newer format version
```

I am working with Godot 4.3dev6 (living on the edge!). Can you give it a try?

EDIT: I will add a comment in the README concerning the version.

**Comment by loic35** [comment]
Confirmed, it works with 4.3dev6 not 4.2.2
